"""
Canonical statement schema and GAAP tag mappings.

- `CANONICAL_LINE_ITEMS` defines the allowed statement/line-item pairs.
- `TAG_MAP` maps us-gaap tags (and common synonyms) to canonical line items.
- `STATEMENT_DISPLAY_ORDER` provides a stable UI/API ordering hint.
"""
from typing import Dict, List, Set, Tuple

# Allowed statements and their canonical line items.
CANONICAL_LINE_ITEMS: Dict[str, Set[str]] = {
    "income_statement": {
        "revenue",
        "cogs",
        "gross_profit",
        "r_and_d",
        "sga",
        "operating_expenses",
        "operating_income",
        "interest_income",
        "interest_expense",
        "other_income_expense",
        "pre_tax_income",
        "income_tax_expense",
        "net_income",
        "ebitda",
        "total_expenses",
        "eps_basic",
        "eps_diluted",
        "shares_basic",
        "shares_diluted",
        "shares_outstanding",
    },
    "balance_sheet": {
        "cash",
        "short_term_investments",
        "accounts_receivable",
        "inventory",
        "prepaid_expenses",
        "other_assets_current",
        "assets_current",
        "other_assets_noncurrent",
        "assets_noncurrent",
        "assets",
        "ppe",
        "goodwill",
        "intangible_assets",
        "accounts_payable",
        "accrued_expenses",
        "deferred_revenue_current",
        "deferred_revenue_noncurrent",
        "other_liabilities_current",
        "liabilities_current",
        "other_liabilities_noncurrent",
        "liabilities_noncurrent",
        "liabilities",
        "debt_current",
        "debt_long_term",
        "equity",
        "retained_earnings",
        "treasury_stock",
        "minority_interest",
        "liabilities_equity",
    },
    "cash_flow": {
        "net_income",
        "depreciation_amortization",
        "stock_compensation",
        "change_working_capital",
        "cfo",
        "capex",
        "acquisitions",
        "cfi",
        "dividends_paid",
        "share_repurchases",
        "debt_issued",
        "debt_repaid",
        "cff",
        "fx_on_cash",
        "change_in_cash",
        "change_in_restricted_cash",
    },
}

# Preferred display order for UI presentation.
STATEMENT_DISPLAY_ORDER: Dict[str, List[str]] = {
    "income_statement": [
        "revenue",
        "cogs",
        "gross_profit",
        "r_and_d",
        "sga",
        "operating_expenses",
        "operating_income",
        "interest_income",
        "interest_expense",
        "other_income_expense",
        "pre_tax_income",
        "income_tax_expense",
        "net_income",
        "ebitda",
        "total_expenses",
        "eps_basic",
        "eps_diluted",
        "shares_basic",
        "shares_diluted",
        "shares_outstanding",
    ],
    "balance_sheet": [
        "cash",
        "short_term_investments",
        "accounts_receivable",
        "inventory",
        "prepaid_expenses",
        "other_assets_current",
        "assets_current",
        "other_assets_noncurrent",
        "assets_noncurrent",
        "assets",
        "ppe",
        "goodwill",
        "intangible_assets",
        "accounts_payable",
        "accrued_expenses",
        "deferred_revenue_current",
        "deferred_revenue_noncurrent",
        "other_liabilities_current",
        "liabilities_current",
        "other_liabilities_noncurrent",
        "liabilities_noncurrent",
        "liabilities",
        "debt_current",
        "debt_long_term",
        "equity",
        "retained_earnings",
        "treasury_stock",
        "minority_interest",
        "liabilities_equity",
    ],
    "cash_flow": [
        "net_income",
        "depreciation_amortization",
        "stock_compensation",
        "change_working_capital",
        "cfo",
        "capex",
        "acquisitions",
        "cfi",
        "dividends_paid",
        "share_repurchases",
        "debt_issued",
        "debt_repaid",
        "cff",
        "fx_on_cash",
        "change_in_restricted_cash",
        "change_in_cash",
    ],
}

# GAAP tag → (line_item, statement). A tag may appear multiple times; keep the first match as the preferred mapping.
TAG_MAP: Dict[str, Tuple[str, str]] = {
    # Income statement
    "us-gaap:Revenues": ("revenue", "income_statement"),
    "us-gaap:SalesRevenueNet": ("revenue", "income_statement"),
    "us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax": ("revenue", "income_statement"),
    "us-gaap:RevenueFromContractWithCustomerIncludingAssessedTax": ("revenue", "income_statement"),
    "us-gaap:NetSales": ("revenue", "income_statement"),
    "us-gaap:RevenuesNetOfInterestExpense": ("revenue", "income_statement"),
    "us-gaap:TotalRevenues": ("revenue", "income_statement"),
    "us-gaap:SalesRevenueGoodsNet": ("revenue", "income_statement"),
    "us-gaap:SalesRevenueServicesNet": ("revenue", "income_statement"),
    "us-gaap:OperatingRevenue": ("revenue", "income_statement"),
    "us-gaap:CostOfRevenue": ("cogs", "income_statement"),
    "us-gaap:CostOfGoodsAndServicesSold": ("cogs", "income_statement"),
    "us-gaap:CostOfGoodsSold": ("cogs", "income_statement"),
    "us-gaap:CostOfSales": ("cogs", "income_statement"),
    "us-gaap:CostOfServices": ("cogs", "income_statement"),
    "us-gaap:GrossProfit": ("gross_profit", "income_statement"),
    "us-gaap:ResearchAndDevelopmentExpense": ("r_and_d", "income_statement"),
    "us-gaap:ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost": ("r_and_d", "income_statement"),
    "us-gaap:SellingGeneralAndAdministrativeExpense": ("sga", "income_statement"),
    "us-gaap:SellingAndMarketingExpense": ("sga", "income_statement"),
    "us-gaap:GeneralAndAdministrativeExpense": ("sga", "income_statement"),
    "us-gaap:OperatingExpenses": ("operating_expenses", "income_statement"),
    "us-gaap:OperatingCostsAndExpenses": ("total_expenses", "income_statement"),
    "us-gaap:OperatingIncomeLoss": ("operating_income", "income_statement"),
    "us-gaap:InterestIncomeExpenseNonoperatingNet": ("interest_income", "income_statement"),
    "us-gaap:InterestIncome": ("interest_income", "income_statement"),
    "us-gaap:InterestIncomeExpenseNet": ("interest_income", "income_statement"),
    "us-gaap:InterestExpenseIncomeNet": ("interest_expense", "income_statement"),
    "us-gaap:InterestAndDebtExpense": ("interest_expense", "income_statement"),
    "us-gaap:InterestExpense": ("interest_expense", "income_statement"),
    "us-gaap:InterestExpenseNonoperating": ("interest_expense", "income_statement"),
    "us-gaap:InterestExpenseDebt": ("interest_expense", "income_statement"),
    "us-gaap:NonoperatingIncomeExpense": ("other_income_expense", "income_statement"),
    "us-gaap:OtherNonoperatingIncomeExpense": ("other_income_expense", "income_statement"),
    "us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments": (
        "pre_tax_income",
        "income_statement",
    ),
    "us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxes": ("pre_tax_income", "income_statement"),
    "us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest": (
        "pre_tax_income",
        "income_statement",
    ),
    "us-gaap:IncomeTaxExpenseBenefit": ("income_tax_expense", "income_statement"),
    "us-gaap:IncomeTaxExpenseBenefitContinuingOperations": ("income_tax_expense", "income_statement"),
    # Net income used in both IS and CF starting line; map to both.
    "us-gaap:NetIncomeLoss": [("net_income", "income_statement"), ("net_income", "cash_flow")],
    "us-gaap:ProfitLoss": ("net_income", "income_statement"),
    "us-gaap:IncomeLossFromContinuingOperations": ("net_income", "income_statement"),
    "us-gaap:CostsAndExpenses": ("total_expenses", "income_statement"),
    "us-gaap:EarningsPerShareBasic": ("eps_basic", "income_statement"),
    "us-gaap:EarningsPerShareDiluted": ("eps_diluted", "income_statement"),
    "us-gaap:WeightedAverageNumberOfSharesOutstandingBasic": ("shares_basic", "income_statement"),
    "us-gaap:WeightedAverageNumberOfDilutedSharesOutstanding": ("shares_diluted", "income_statement"),
    "us-gaap:WeightedAverageNumberOfSharesOutstandingBasicAndDiluted": ("shares_diluted", "income_statement"),
    "us-gaap:CommonStockSharesOutstanding": ("shares_outstanding", "income_statement"),
    "us-gaap:CommonStockSharesIssued": ("shares_outstanding", "income_statement"),
    "us-gaap:WeightedAverageNumberOfSharesOutstanding": ("shares_outstanding", "income_statement"),
    # Balance sheet
    "us-gaap:Assets": ("assets", "balance_sheet"),
    "us-gaap:AssetsCurrent": ("assets_current", "balance_sheet"),
    "us-gaap:AssetsNoncurrent": ("assets_noncurrent", "balance_sheet"),
    "us-gaap:OtherAssetsNoncurrent": ("assets_noncurrent", "balance_sheet"),
    "us-gaap:CashAndCashEquivalentsAtCarryingValue": ("cash", "balance_sheet"),
    "us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents": ("cash", "balance_sheet"),
    "us-gaap:ShortTermInvestments": ("short_term_investments", "balance_sheet"),
    "us-gaap:MarketableSecuritiesCurrent": ("short_term_investments", "balance_sheet"),
    "us-gaap:AccountsReceivableNetCurrent": ("accounts_receivable", "balance_sheet"),
    "us-gaap:AccountsReceivableNet": ("accounts_receivable", "balance_sheet"),
    "us-gaap:AccountsReceivable": ("accounts_receivable", "balance_sheet"),
    "us-gaap:InventoryNet": ("inventory", "balance_sheet"),
    "us-gaap:PrepaidExpenseAndOtherAssetsCurrent": ("prepaid_expenses", "balance_sheet"),
    "us-gaap:PrepaidExpense": ("prepaid_expenses", "balance_sheet"),
    "us-gaap:PrepaidExpenseCurrent": ("prepaid_expenses", "balance_sheet"),
    "us-gaap:OtherAssetsCurrent": ("other_assets_current", "balance_sheet"),
    "us-gaap:OtherAssetsNoncurrent": ("other_assets_noncurrent", "balance_sheet"),
    "us-gaap:PropertyPlantAndEquipmentNet": ("ppe", "balance_sheet"),
    "us-gaap:Goodwill": ("goodwill", "balance_sheet"),
    "us-gaap:IntangibleAssetsNetExcludingGoodwill": ("intangible_assets", "balance_sheet"),
    "us-gaap:IntangibleAssetsNet": ("intangible_assets", "balance_sheet"),
    "us-gaap:AccountsPayableCurrent": ("accounts_payable", "balance_sheet"),
    "us-gaap:AccountsPayable": ("accounts_payable", "balance_sheet"),
    "us-gaap:AccruedLiabilitiesCurrent": ("accrued_expenses", "balance_sheet"),
    "us-gaap:AccruedLiabilities": ("accrued_expenses", "balance_sheet"),
    "us-gaap:AccruedLiabilitiesAndOtherCurrent": ("accrued_expenses", "balance_sheet"),
    "us-gaap:AccruedLiabilitiesAndOther": ("accrued_expenses", "balance_sheet"),
    "us-gaap:DeferredRevenueAndDepositsCurrent": ("deferred_revenue_current", "balance_sheet"),
    "us-gaap:DeferredRevenueCurrent": ("deferred_revenue_current", "balance_sheet"),
    "us-gaap:ContractWithCustomerLiabilityCurrent": ("deferred_revenue_current", "balance_sheet"),
    "us-gaap:DeferredRevenueAndDepositsNoncurrent": ("deferred_revenue_noncurrent", "balance_sheet"),
    "us-gaap:DeferredRevenueNoncurrent": ("deferred_revenue_noncurrent", "balance_sheet"),
    "us-gaap:ContractWithCustomerLiabilityNoncurrent": ("deferred_revenue_noncurrent", "balance_sheet"),
    "us-gaap:OtherLiabilitiesCurrent": ("other_liabilities_current", "balance_sheet"),
    "us-gaap:OtherLiabilitiesNoncurrent": ("other_liabilities_noncurrent", "balance_sheet"),
    "us-gaap:LiabilitiesCurrent": ("liabilities_current", "balance_sheet"),
    "us-gaap:LiabilitiesNoncurrent": ("liabilities_noncurrent", "balance_sheet"),
    "us-gaap:OtherLiabilitiesNoncurrent": ("liabilities_noncurrent", "balance_sheet"),
    "us-gaap:DeferredTaxLiabilitiesNoncurrent": ("liabilities_noncurrent", "balance_sheet"),
    "us-gaap:Liabilities": ("liabilities", "balance_sheet"),
    "us-gaap:LongTermDebtCurrent": ("debt_current", "balance_sheet"),
    "us-gaap:DebtCurrent": ("debt_current", "balance_sheet"),
    "us-gaap:ShortTermBorrowings": ("debt_current", "balance_sheet"),
    "us-gaap:LongTermDebtNoncurrent": ("debt_long_term", "balance_sheet"),
    "us-gaap:DebtNoncurrent": ("debt_long_term", "balance_sheet"),
    "us-gaap:LongTermDebtAndCapitalLeaseObligations": ("debt_long_term", "balance_sheet"),
    "us-gaap:LongTermDebtAndCapitalLeaseObligationsCurrent": ("debt_current", "balance_sheet"),
    "us-gaap:StockholdersEquity": ("equity", "balance_sheet"),
    "us-gaap:StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest": ("equity", "balance_sheet"),
    "us-gaap:RetainedEarningsAccumulatedDeficit": ("retained_earnings", "balance_sheet"),
    "us-gaap:TreasuryStockValue": ("treasury_stock", "balance_sheet"),
    "us-gaap:TreasuryStockCommon": ("treasury_stock", "balance_sheet"),
    "us-gaap:TreasuryStockCommonSharesValue": ("treasury_stock", "balance_sheet"),
    "us-gaap:TreasuryStockCommonStockValue": ("treasury_stock", "balance_sheet"),
    "us-gaap:MinorityInterest": ("minority_interest", "balance_sheet"),
    "us-gaap:NoncontrollingInterest": ("minority_interest", "balance_sheet"),
    "us-gaap:LiabilitiesAndStockholdersEquity": ("liabilities_equity", "balance_sheet"),
    "us-gaap:LiabilitiesAndEquity": ("liabilities_equity", "balance_sheet"),
    "us-gaap:LiabilitiesAndStockholdersEquityIncludingPortionAttributableToNoncontrollingInterest": (
        "liabilities_equity",
        "balance_sheet",
    ),
    # Cash flow
    "us-gaap:DepreciationDepletionAndAmortization": ("depreciation_amortization", "cash_flow"),
    "us-gaap:DepreciationAndAmortization": ("depreciation_amortization", "cash_flow"),
    "us-gaap:DepreciationAmortizationAndAccretionNet": ("depreciation_amortization", "cash_flow"),
    "us-gaap:ShareBasedCompensation": ("stock_compensation", "cash_flow"),
    "us-gaap:ShareBasedCompensationExpense": ("stock_compensation", "cash_flow"),
    "us-gaap:IncreaseDecreaseInOperatingCapital": ("change_working_capital", "cash_flow"),
    "us-gaap:IncreaseDecreaseInOperatingAssetsAndLiabilities": ("change_working_capital", "cash_flow"),
    "us-gaap:IncreaseDecreaseInOtherOperatingAssets": ("change_working_capital", "cash_flow"),
    "us-gaap:IncreaseDecreaseInOtherOperatingLiabilities": ("change_working_capital", "cash_flow"),
    "us-gaap:NetCashProvidedByUsedInOperatingActivities": ("cfo", "cash_flow"),
    "us-gaap:NetCashProvidedByUsedInOperatingActivitiesContinuingOperations": ("cfo", "cash_flow"),
    "us-gaap:PaymentsToAcquirePropertyPlantAndEquipment": ("capex", "cash_flow"),
    "us-gaap:PaymentsToAcquireProductiveAssets": ("capex", "cash_flow"),
    "us-gaap:PaymentsToAcquireBusinesses": ("acquisitions", "cash_flow"),
    "us-gaap:PaymentsToAcquireBusinessesNetOfCashAcquired": ("acquisitions", "cash_flow"),
    "us-gaap:PaymentsToAcquireBusinessesAndIntangibles": ("acquisitions", "cash_flow"),
    "us-gaap:NetCashProvidedByUsedInInvestingActivities": ("cfi", "cash_flow"),
    "us-gaap:NetCashProvidedByUsedInInvestingActivitiesContinuingOperations": ("cfi", "cash_flow"),
    "us-gaap:PaymentsOfDividends": ("dividends_paid", "cash_flow"),
    "us-gaap:PaymentsOfDividendsCommonStock": ("dividends_paid", "cash_flow"),
    "us-gaap:PaymentsOfDividendsCommonStockAndPreferredStock": ("dividends_paid", "cash_flow"),
    "us-gaap:PaymentsForRepurchaseOfCommonStock": ("share_repurchases", "cash_flow"),
    "us-gaap:PaymentsForRepurchaseOfCommonStockIncludingTreasuryStock": ("share_repurchases", "cash_flow"),
    "us-gaap:ProceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet": ("debt_issued", "cash_flow"),
    "us-gaap:ProceedsFromShortTermDebt": ("debt_issued", "cash_flow"),
    "us-gaap:ProceedsFromLinesOfCredit": ("debt_issued", "cash_flow"),
    "us-gaap:RepaymentsOfLongTermDebt": ("debt_repaid", "cash_flow"),
    "us-gaap:RepaymentsOfShortTermDebt": ("debt_repaid", "cash_flow"),
    "us-gaap:NetCashProvidedByUsedInFinancingActivities": ("cff", "cash_flow"),
    "us-gaap:NetCashProvidedByUsedInFinancingActivitiesContinuingOperations": ("cff", "cash_flow"),
    "us-gaap:ProceedsFromIssuanceOfLongTermDebt": ("debt_issued", "cash_flow"),
    "us-gaap:ProceedsFromIssuanceOfDebt": ("debt_issued", "cash_flow"),
    "us-gaap:RepaymentsOfDebt": ("debt_repaid", "cash_flow"),
    "us-gaap:RepaymentsOfLongTermDebtAndCapitalLeaseObligations": ("debt_repaid", "cash_flow"),
    "us-gaap:EffectOfExchangeRateOnCashAndCashEquivalents": ("fx_on_cash", "cash_flow"),
    "us-gaap:EffectOfExchangeRateOnCashAndCashEquivalentsAndRestrictedCash": ("fx_on_cash", "cash_flow"),
    "us-gaap:EffectOfExchangeRateOnCashAndCashEquivalentsPeriodIncreaseDecrease": ("fx_on_cash", "cash_flow"),
    "us-gaap:IncreaseDecreaseInCashAndCashEquivalents": ("change_in_cash", "cash_flow"),
    "us-gaap:NetIncreaseDecreaseInCashAndCashEquivalents": ("change_in_cash", "cash_flow"),
    "us-gaap:CashAndCashEquivalentsPeriodIncreaseDecrease": ("change_in_cash", "cash_flow"),
    "us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecrease": ("change_in_cash", "cash_flow"),
    "us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect": (
        "change_in_cash",
        "cash_flow",
    ),
    "us-gaap:NetIncreaseDecreaseInCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents": (
        "change_in_cash",
        "cash_flow",
    ),
    "us-gaap:NetCashProvidedByUsedInContinuingOperations": ("cfo", "cash_flow"),
    "us-gaap:NetCashProvidedByUsedInOperatingActivitiesAndNetIncreaseDecreaseInBankOverdrafts": ("cfo", "cash_flow"),
    "us-gaap:NetCashProvidedByUsedInOperatingActivitiesAndNetIncreaseDecreaseInBankOverdraftsContinuingOperations": ("cfo", "cash_flow"),
    "us-gaap:NetChangeInRestrictedCash": ("change_in_restricted_cash", "cash_flow"),
    "us-gaap:IncreaseDecreaseInRestrictedCashAndCashEquivalents": ("change_in_restricted_cash", "cash_flow"),
    "us-gaap:NetIncreaseDecreaseInRestrictedCashAndCashEquivalents": ("change_in_restricted_cash", "cash_flow"),
}


def allowed_statements() -> Set[str]:
    return set(CANONICAL_LINE_ITEMS.keys())


def allowed_line_items() -> Dict[str, Set[str]]:
    return CANONICAL_LINE_ITEMS
